#SPDX-License-Identifier: MIT-0
---
# tasks file for SQLuser
#- name: Installer passlib si absent
 # pipx:
 #   name: passlib
#    state: present
- name:  python  mila installé
  ansible.builtin.apt:
    name: python3
    state: present
- name:  mariadb mila installé
  ansible.builtin.apt:
    name: mariadb-server
    state: present
- name:  Mysql  mila installé
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Mysql mila running
  ansible.builtin.service:
    name: mysql
    state: started
- name:  mariaDB  mila running
  ansible.builtin.service:
    name: mariadb
    state: present


- name: Create mysql users
  community.mysql.mysql_user:
    name: "{{ item.name}}"
    password: >-
      {{ item.mdp_plaintext | password_hash( item.hash_mode , item.salt) }}
    host: localhost
    login_unix_socket: /run/mysqld/mysqld.sock   
 #   create_home: yes
    column_case_sensitive: false
    update_password: on_create
  loop: "{{sqlusers}}"
