#SPDX-License-Identifier: MIT-0
---
# tasks file for SQLuser
- name: Vérification 
  pip:
    name: pymysql
    executable: pip3

- name : Creat mysql users
  community.mysql.mysql_user:
    name: "{{ item.name}}"
    password: >-
      {{ item.mdp_plaintext | password_hash( item.hash_mode , item.salt) }}
    host: localhost
    login_unix_socket: /run/mysqld/mysqld.sock   
 #   create_home: yes
    update_password: on_create
  loop: "{{sqlusers}}"
